# Las Vegas Hotel Ratings

In [1]:
#dependencies and setup

import pandas as pd

#files to load
datafiniti = 'Resources/Datafiniti_Hotel_Reviews.csv'
datafiniti_jun = 'Resources/Datafiniti_Hotel_Reviews_Jun19.csv'
lvtrip_advisor = 'Resources/lasvegas_tripadvisor.csv'
reviews = 'Resources/reviews.csv'


#Read files and store into dataframe

datafiniti_df = pd.read_csv(datafiniti)
datafiniti_jun_df = pd.read_csv(datafiniti_jun)
lvtrip_advisor_df = pd.read_csv(lvtrip_advisor)
reviews_df = pd.read_csv(reviews)
reviews_df.head()

,address,categories,city,country,latitude,longitude,name,postalCode,province,reviews.date,reviews.dateAdded,reviews.doRecommend,reviews.id,reviews.rating,reviews.text,reviews.title,reviews.userCity,reviews.username,reviews.userProvince
0,Riviera San Nicol 11/a,Hotels,Mableton,US,45.421611,12.376187,Hotel Russo Palace,30126,GA,2013-09-22T00:00:00Z,2016-10-24T00:00:25Z,NaN,NaN,4.0,Pleasant 10 min walk along the sea front to th...,Good location away from the crouds,NaN,Russ (kent),NaN
1,Riviera San Nicol 11/a,Hotels,Mableton,US,45.421611,12.376187,Hotel Russo Palace,30126,GA,2015-04-03T00:00:00Z,2016-10-24T00:00:25Z,NaN,NaN,5.0,Really lovely hotel. Stayed on the very top fl...,Great hotel with Jacuzzi bath!,NaN,A Traveler,NaN
2,Riviera San Nicol 11/a,Hotels,Mableton,US,45.421611,12.376187,Hotel Russo Palace,30126,GA,2014-05-13T00:00:00Z,2016-10-24T00:00:25Z,NaN,NaN,5.0,Ett mycket bra hotell. Det som drog ner betyge...,Lugnt l��ge,NaN,Maud,NaN
3,Riviera San Nicol 11/a,Hotels,Mableton,US,45.421611,12.376187,Hotel Russo Palace,30126,GA,2013-10-27T00:00:00Z,2016-10-24T00:00:25Z,NaN,NaN,5.0,We stayed here for four nights in October. The...,Good location on the Lido.,NaN,Julie,NaN
4,Riviera San Nicol 11/a,Hotels,Mableton,US,45.421611,12.376187,Hotel Russo Palace,30126,GA,2015-03-05T00:00:00Z,2016-10-24T00:00:25Z,NaN,NaN,5.0,We stayed here for four nights in October. The...,������ ���������������,NaN,sungchul,NaN

In [41]:
#delete extraneous columns from review
del_rev_df = reviews_df.drop(columns=['reviews.text','categories','reviews.userCity','reviews.username','reviews.userProvince','reviews.dateAdded','reviews.doRecommend','reviews.id','address','latitude', 'longitude'])
del_rev_df.head()

,city,country,name,postalCode,province,reviews.date,reviews.rating,reviews.title
0,Mableton,US,Hotel Russo Palace,30126,GA,2013-09-22T00:00:00Z,4.0,Good location away from the crouds
1,Mableton,US,Hotel Russo Palace,30126,GA,2015-04-03T00:00:00Z,5.0,Great hotel with Jacuzzi bath!
2,Mableton,US,Hotel Russo Palace,30126,GA,2014-05-13T00:00:00Z,5.0,Lugnt l��ge
3,Mableton,US,Hotel Russo Palace,30126,GA,2013-10-27T00:00:00Z,5.0,Good location on the Lido.
4,Mableton,US,Hotel Russo Palace,30126,GA,2015-03-05T00:00:00Z,5.0,������ ���������������

In [42]:
#create dataframe - vegas specific with related columns
vegas_df = del_rev_df[del_rev_df['city']=='Las Vegas']
vegas_df

,city,country,name,postalCode,province,reviews.date,reviews.rating,reviews.title
10112,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-07-17T00:00:00Z,4.0,NaN
10113,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-07-15T00:00:00Z,4.0,NaN
10114,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-07-13T00:00:00Z,3.0,not good not bad
10115,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-07-24T00:00:00Z,4.0,not good not bad
10116,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-07-15T00:00:00Z,4.0,Las Vegas Vacation
...,...,...,...,...,...,...,...,...
10398,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-09-14T00:00:00Z,4.0,Great Value and Location For Downtown
10399,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-08-25T00:00:00Z,1.0,"Dirty room, rude staff"
10400,Las Vegas,US,Plaza Hotel and Casino - Las Vegas,89101,NV,2016-06-16T00:00:00Z,3.0,Pretty convenient for what we needed.
31774,Las Vegas,US,Outside Inn,89117,NV,2007-09-25T00:00:00Z,3.0,Buy beer by the bottle
31775,Las Vegas,US,Outside Inn,89117,NV,2007-08-28T00:00:00Z,1.0,Avoid Like the Plague!

In [43]:
#merge datafiniti - two datasets
frames = [datafiniti_df, datafiniti_jun_df]
datafin = pd.concat(frames)
datafin.head()

,id,dateAdded,dateUpdated,address,categories,primaryCategories,city,country,keys,latitude,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sourceURLs,websites,reviews.dateAdded
0,AVwdygbvIN2L1WUfzOvF,2017-04-18T10:57:07Z,2018-06-26T03:04:02Z,621 Saint Louis St,"Hotels,Resort,Lodging,Hotel",Accommodation & Food Services,New Orleans,US,us/la/neworleans/621saintlouisst/505139068,29.956219,...,4.0,http://www.citysearch.com/review/4440930%25252...,Found the hotel to be conveniently located and...,Enjoyed My Stay,NaN,NaN,Governer,https://www.tripadvisor.com/Hotel_Review-g6086...,https://www.omnihotels.com/hotels/new-orleans-...,NaN
1,AWEw3i5yRxPSIh2RsYCd,2018-01-26T05:08:08Z,2018-08-27T16:47:40Z,9090 Alta Dr,"Hotels,Casinos,Resorts,Casino,Lodging,Hotel,Re...",Accommodation & Food Services,Las Vegas,US,us/nv/lasvegas/9090altadr/-564462433,36.168830,...,3.0,https://www.tripadvisor.com/Hotel_Review-g4596...,Stayed at the Suncoast for a week in Feb. 2003...,Who Maid the Bed,Clinton,NaN,A TripAdvisor Member,https://www.tripadvisor.com/Hotel_Review-g4596...,"http://www.bconnectedonline.com,http://www.sun...",NaN
2,AWEw3i5yRxPSIh2RsYCd,2018-01-26T05:08:08Z,2018-08-27T16:47:40Z,9090 Alta Dr,"Hotels,Casinos,Resorts,Casino,Lodging,Hotel,Re...",Accommodation & Food Services,Las Vegas,US,us/nv/lasvegas/9090altadr/-564462433,36.168830,...,5.0,https://www.tripadvisor.com/Hotel_Review-g4596...,"With the movie theater, kids babysitter facili...","What a great place for kids, exceptional offst...",detroit,michigan,Nerissa W,https://www.tripadvisor.com/Hotel_Review-g4596...,"http://www.bconnectedonline.com,http://www.sun...",NaN
3,AVwdIPxpkufWRAb52lqx,2017-03-31T20:41:49Z,2018-08-27T16:54:39Z,1730 S State College Blvd,"Hotels,Corporate Lodging,Lodging,Hotels-Apartm...",Accommodation & Food Services,Anaheim,US,us/ca/anaheim/1730sstatecollegeblvd/-1298838898,33.804844,...,5.0,https://www.tripadvisor.com/Hotel_Review-g2909...,The two bedroom suites worked out very well fo...,Great family place to stay in Anaheim,Massillon,Ohio,Venture12076,https://www.tripadvisor.com/Hotel_Review-g2909...,http://www.marriott.com/towneplace-suites/trav...,NaN
4,AVwdIPxpkufWRAb52lqx,2017-03-31T20:41:49Z,2018-08-27T16:54:39Z,1730 S State College Blvd,"Hotels,Corporate Lodging,Lodging,Hotels-Apartm...",Accommodation & Food Services,Anaheim,US,us/ca/anaheim/1730sstatecollegeblvd/-1298838898,33.804844,...,5.0,https://www.tripadvisor.com/Hotel_Review-g2909...,We stayed in a two bedroom apartment during ou...,Perfect for families,Perth,NaN,A TripAdvisor Member,https://www.tripadvisor.com/Hotel_Review-g2909...,http://www.marriott.com/towneplace-suites/trav...,NaN

In [53]:
#delete extraneous columns from datafin
datafin_del_df = datafin.drop(columns=['keys', 'latitude', 'reviews.text', 'reviews.userProvince', 'reviews.username', 'sourceURLs', 'websites', 'reviews.dateAdded'])
datafin_del_df.head()
datafin_del_df2 = datafin_del_df.drop(columns=['longitude', 'address', 'reviews.sourceURLs','reviews.dateSeen', 'primaryCategories', 'categories', 'dateAdded', 'dateUpdated'])
datafin_del_df2.head()

,id,city,country,name,postalCode,province,reviews.date,reviews.rating,reviews.title,reviews.userCity
0,AVwdygbvIN2L1WUfzOvF,New Orleans,US,Omni Royal Orleans,70130,LA,2002-07-24T00:00:00Z,4.0,Enjoyed My Stay,NaN
1,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2003-02-23T00:00:00.000Z,3.0,Who Maid the Bed,Clinton
2,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2003-07-15T00:00:00.000Z,5.0,"What a great place for kids, exceptional offst...",detroit
3,AVwdIPxpkufWRAb52lqx,Anaheim,US,TownePlace Suites Anaheim Maingate Near Angel ...,92806-6022,CA,2004-03-01T00:00:00.000Z,5.0,Great family place to stay in Anaheim,Massillon
4,AVwdIPxpkufWRAb52lqx,Anaheim,US,TownePlace Suites Anaheim Maingate Near Angel ...,92806-6022,CA,2004-06-24T00:00:00.000Z,5.0,Perfect for families,Perth

In [54]:
#display only las vegas hotels
#create dataframe - vegas specific with related columns
datafin_vegas_df = datafin_del_df2[datafin_del_df2['city']=='Las Vegas']
datafin_vegas_df

,id,city,country,name,postalCode,province,reviews.date,reviews.rating,reviews.title,reviews.userCity
1,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2003-02-23T00:00:00.000Z,3.0,Who Maid the Bed,Clinton
2,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2003-07-15T00:00:00.000Z,5.0,"What a great place for kids, exceptional offst...",detroit
12,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2005-05-09T00:00:00.000Z,4.0,Far From Strip but Nice,Orlando
23,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2005-09-27T00:00:00.000Z,5.0,more for your money!!!!!,Stockton
54,AWEw3i5yRxPSIh2RsYCd,Las Vegas,US,Suncoast Hotel and Casino,89145-8508,NV,2007-03-12T00:00:00.000Z,3.0,Suncoast Hotel mixed review,Sacramento
...,...,...,...,...,...,...,...,...,...,...
6415,AVwc5_kzkufWRAb50R9q,Las Vegas,US,Delano Las Vegas,89119,NV,2016-06-21T00:00:00Z,4.0,"Same vibe, lacking food options",Redwood City
6467,AVwc5_kzkufWRAb50R9q,Las Vegas,US,Delano Las Vegas,89119,NV,2016-06-26T00:00:00Z,4.0,Nice Hotel,Baton Rouge
7037,AWKkSsJma4HuVbedPTf_,Las Vegas,US,Marriott's Grand Chateau,89109,NV,2016-09-13T00:00:00.000Z,5.0,Great suite for families,Alta Loma
7711,AWKkSsJma4HuVbedPTf_,Las Vegas,US,Marriott's Grand Chateau,89109,NV,2017-03-13T00:00:00.000Z,5.0,Great week in Vegas,Johnston
8137,AWKkSsJma4HuVbedPTf_,Las Vegas,US,Marriott's Grand Chateau,89109,NV,2017-06-18T00:00:00.000Z,5.0,Loved our just renovated room.,Northampton

In [23]:
#identify dups in dataframe on id column
#By default, for each set of duplicated values, 
#the first occurrence is set on False and all others on True.
dups = datafin.duplicated(subset=['id'])
dups

0       False
1       False
2        True
3       False
4        True
        ...
9995     True
9996    False
9997     True
9998     True
9999     True
Length: 20000, dtype: bool